#=========================================================Testing new management server deployment
deploy-code-job-development-mgmt:
     stage: deploy
     tags:
       - learnovia
       - backend
       - mgmt
     only:
       - development
     script:
       - ansible-playbook /backup/playbooks/development-backend.yml

